keys: 
  - &EPFLMacbook age1d25zk4n2af9ftmuzz4zz6rk3fx7arwz3m3sqfa7ht2aq9v76fc8q29g7ze
  - &nixserver age19fr9m688l4hu2vyaymwns8f494kruwt3hptsp9qvpf3wjunvzg3q2dze75
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
        - *EPFLMacbook
        - *nixserver
